insert into user_account (login_id, password, name, phone_number) values ('honey', '$2a$10$F36MOa0H6ybdaiinlSB/QuC93xiXNB1KNjY3.Qh5En42KLLIX48Bq', '이재헌', '157-398-4256');
insert into user_account (login_id, password, name, phone_number) values ('user', '$2a$10$PVcPh4eLJ1fOqPAnJV3MAuMIf733hYOr8kyUb7LVDud3dXNSDMz0i', '고객', '157-398-4256');
insert into user_account (login_id, password, name, phone_number) values ('manager', '$2a$10$lgl3IqIuB3S4kOz2WB9X7.E9hwQgoyQZ3.vElBObqPRNdzr6CZ8gu', '매니저', '157-398-4256');

insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-21', '17:00', 'Golf', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-29', '13:30', 'Grand Cherokee', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-25', '9:30', 'Arnage', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-28', '16:30', 'Insight', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-16', '11:30', 'Metro', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-17', '9:30', 'SL-Class', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-22', '11:30', 'Galant', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-18', '12:30', 'Viper', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-23', '14:00', 'Crown Victoria', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-23', '17:00', 'CR-Z', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-16', '15:30', '57', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-26', '14:30', '240SX', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-25', '17:30', 'Sentra', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-22', '15:30', 'Wrangler', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-28', '11:30', '928', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-16', '12:00', 'Lumina', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-24', '9:30', 'Stealth', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-26', '12:30', '745', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-27', '12:30', 'IS-F', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-22', '16:00', 'Continental', 'READY');

insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-17', '15:30', '3500', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-22', '17:00', 'Lumina', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-29', '13:00', 'DeVille', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-15', '13:30', 'G-Series G30', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-24', '11:30', 'Commander', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-29', '13:30', 'M', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-25', '16:30', 'Firebird', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-21', '13:30', 'Riviera', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-26', '16:30', 'B-Series', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-28', '13:30', 'Explorer', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-16', '16:30', '525', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-29', '10:30', 'LeBaron', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-18', '10:00', 'S4', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-23', '11:00', 'Grand Marquis', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-19', '12:30', 'CTS', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-23', '17:30', 'Sable', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-22', '15:30', 'New Beetle', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-24', '14:00', 'Suburban 1500', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-22', '16:30', 'Range Rover', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-21', '9:30', 'S90', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-27', '10:00', 'Sierra 1500', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-26', '17:00', 'Silverado 3500', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-15', '13:30', 'Bravada', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-15', '11:30', 'Mustang', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-16', '12:30', 'Dakota', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-24', '12:00', '626', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-24', '16:00', 'A8', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-22', '13:30', 'Tiburon', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-24', '9:00', 'Corvette', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-16', '10:30', 'Ram 2500', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-16', '16:00', 'M3', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-19', '10:30', 'LeMans', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-27', '16:30', 'Cooper', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-16', '16:00', 'Monte Carlo', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-20', '12:00', 'Mountaineer', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-26', '17:00', 'E-Series', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-28', '15:00', 'Baja', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-25', '10:00', 'Thunderbird', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-28', '13:00', 'Corolla', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-26', '12:30', 'Tempo', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-28', '15:00', 'Sky', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-24', '17:00', 'CR-V', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-17', '12:30', 'Diamante', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-25', '12:00', 'Mustang', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-19', '14:30', 'Baja', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-23', '15:00', 'Range Rover Sport', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-27', '17:00', 'Corvette', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-28', '16:30', '600SL', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-27', '9:30', 'Outlander', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-25', '14:00', 'Suburban 2500', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-29', '12:30', 'Insight', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-17', '14:00', 'Tracer', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-27', '14:00', '5 Series', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-22', '16:00', 'Camaro', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-25', '15:30', 'Roadrunner', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-23', '13:00', 'TT', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-21', '15:00', 'C-Class', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-25', '15:00', 'LeSabre', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-22', '12:30', 'Malibu', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-16', '13:00', 'Hearse', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-21', '10:00', '3500 Club Coupe', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-15', '15:00', 'E250', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-22', '11:00', 'CL', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-18', '14:00', 'XL-7', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-25', '12:30', 'D250', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-27', '17:30', 'Justy', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-15', '11:00', 'STS', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-18', '17:00', 'Galant', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-20', '16:00', 'Ciera', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-18', '15:30', 'LeMans', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-29', '14:00', 'Miata MX-5', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-25', '10:30', 'LS Hybrid', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-25', '15:30', 'Galant', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-15', '9:30', 'CX-7', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-28', '15:30', 'LS', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-28', '15:00', 'Millenia', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-25', '15:30', 'Hombre Space', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-25', '10:00', 'Viper RT/10', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-25', '10:00', 'Touareg', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-17', '17:30', 'Element', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-27', '13:00', 'Century', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-21', '14:30', 'Colorado', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-23', '9:00', 'Challenger', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-15', '15:30', 'Ramcharger', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-29', '15:30', 'Element', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-26', '10:30', 'Lancer', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-15', '10:00', 'Murano', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-15', '10:00', 'Yukon XL', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-24', '14:30', '2500', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-29', '10:30', 'F150', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-21', '14:30', 'M-Class', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-22', '14:30', 'Aero 8', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-29', '12:30', 'Bonneville', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-28', '12:00', 'Eclipse', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-24', '16:30', 'A4', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-27', '10:00', '8 Series', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-15', '9:30', 'Capri', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('honey', '2023-06-17', '16:30', 'ES', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('manager', '2023-06-19', '10:30', 'RX-8', 'READY');
insert into reservation (user_account_id, local_date, local_time, memo, reservation_status) values ('user', '2023-06-22', '12:30', 'Forester', 'READY');